version: '3'
services:
  sample-front-nuxt3:
    # build: .
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
